//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartialBase.FakeData.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Currency {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Currency() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MartialBase.FakeData.Resources.Currency", typeof(Currency).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADP;AED;AFA;AFN;ALK;ALL;AMD;ANG;AOA;AOK;AON;AOR;ARA;ARP;ARS;ARY;ATS;AUD;AWG;AYM;AZM;AZN;BAD;BAM;BBD;BDT;BEC;BEF;BEL;BGJ;BGK;BGL;BGN;BHD;BIF;BMD;BND;BOB;BOP;BOV;BRB;BRC;BRE;BRL;BRN;BRR;BSD;BTN;BUK;BWP;BYB;BYN;BYR;BZD;CAD;CDF;CHC;CHE;CHF;CHW;CLF;CLP;CNY;COP;COU;CRC;CSD;CSJ;CSK;CUC;CUP;CVE;CYP;CZK;DDM;DEM;DJF;DKK;DOP;DZD;ECS;ECV;EEK;EGP;ERN;ESA;ESB;ESP;ETB;EUR;FIM;FJD;FKP;FRF;GBP;GEK;GEL;GHC;GHP;GHS;GIP;GMD;GNE;GNF;GNS;GQE;GRD;GTQ;GWE;GWP;GYD;HKD;HNL;HRD;HRK;HTG;HUF;IDR;IEP;ILP;ILR;ILS;INR;IQD;IRR;ISJ;ISK;ITL; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Iso3LetterCodes {
            get {
                return ResourceManager.GetString("Iso3LetterCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghani;Algerian Dinar;Andorran Peseta;Argentine Peso;Armenian Dram;Aruban Florin;Austral;Australian Dollar;Azerbaijan Manat;Azerbaijanian Manat;Bahamian Dollar;Bahraini Dinar;Baht;Balboa;Barbados Dollar;Belarusian Ruble;Belgian Franc;Belize Dollar;Bermudian Dollar;Bolivar;Bolivar Fuerte;Boliviano;Bolívar;Brazilian Real;Brunei Dollar;Bulgarian Lev;Burundi Franc;Cabo Verde Escudo;Canadian Dollar;Cayman Islands Dollar;Cedi;CFA Franc BCEAO;CFA Franc BEAC;CFP Franc;Chilean Peso;Colombian Peso;Comorian Franc;Con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
    }
}
