//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartialBase.FakeData.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Identification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Identification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MartialBase.FakeData.Resources.Identification", typeof(Identification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACDEFGHJKMNPQRTUVWXY.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;B;C;D;E;F;G;H;I;J;K;L;M;N;O;P;Q;R;S;T;U;V;W;X;Z;Y.
        /// </summary>
        internal static string Alphabet {
            get {
                return ResourceManager.GetString("Alphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;2;3;4;5;6;7;8;9;A;C;D;E;F;G;H;J;K;M;N;P;Q;R;T;U;V;W;X;Y.
        /// </summary>
        internal static string Mbi {
            get {
                return ResourceManager.GetString("Mbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;C;D;E;F;G;H;J;K;M;N;P;Q;R;T;U;V;W;X;Y.
        /// </summary>
        internal static string MbiAlphabet {
            get {
                return ResourceManager.GetString("MbiAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;2;3;4;5;6;7;8;9.
        /// </summary>
        internal static string MbiNumeric {
            get {
                return ResourceManager.GetString("MbiNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0;1;2;3;4;5;6;7;8;9.
        /// </summary>
        internal static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;B;C;E;G;H;J;K;L;M;N;O;P;R;S;T;W;X;Z;Y.
        /// </summary>
        internal static string UkNationalInsuranceFirstDigit {
            get {
                return ResourceManager.GetString("UkNationalInsuranceFirstDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG;GB;NK;KN;TN;NT;ZZ.
        /// </summary>
        internal static string UkNationalInsuranceNotAllowedPrefix {
            get {
                return ResourceManager.GetString("UkNationalInsuranceNotAllowedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;B;C;E;G;H;J;K;L;M;N;P;R;S;T;W;X;Z;Y.
        /// </summary>
        internal static string UkNationalInsuranceSecondDigit {
            get {
                return ResourceManager.GetString("UkNationalInsuranceSecondDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;B;C;D.
        /// </summary>
        internal static string UkNationalInsuranceSuffix {
            get {
                return ResourceManager.GetString("UkNationalInsuranceSuffix", resourceCulture);
            }
        }
    }
}
