//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartialBase.FakeData.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Name {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Name() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MartialBase.FakeData.Resources.Name", typeof(Name).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaliyah; Aaron; Abagail; Abbey; Abbie; Abbigail; Abby; Abdiel; Abdul; Abdullah; Abe; Abel; Abelardo; Abigail; Abigale; Abigayle; Abner; Abraham; Ada; Adah; Adalberto; Adaline; Adam; Adan; Addie; Addison; Adela; Adelbert; Adele; Adelia; Adeline; Adell; Adella; Adelle; Aditya; Adolf; Adolfo; Adolph; Adolphus; Adonis; Adrain; Adrian; Adriana; Adrianna; Adriel; Adrien; Adrienne; Afton; Aglae; Agnes; Agustin; Agustina; Ahmad; Ahmed; Aida; Aidan; Aiden; Aileen; Aimee; Aisha; Aiyana; Akeem; Al; Alaina; Alan; Alana [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaliyah; Abagail; Abbey; Abbie; Abbigail; Abby; Abigail; Abigale; Abigayle; Ada; Adah; Adaline; Addie; Adela; Adele; Adelia; Adeline; Adell; Adella; Adelle; Aditya; Adrian; Adriana; Adrianna; Adrien; Adrienne; Agnes; Agustina; Aida; Aileen; Aimee; Aisha; Aiyana; Alaina; Alana; Alanna; Alayna; Alba; Alberta; Albertha; Albina; Alda; Alejandra; Alena; Alene; Alessandra; Alessia; Aletha; Alex; Alexa; Alexandra; Alexandrea; Alexandria; Alexandrine; Alexanne; Alexie; Alexis; Alexys; Alfreda; Ali; Alia; Alice; Ali [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstFemale {
            get {
                return ResourceManager.GetString("FirstFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron; Abdiel; Abdul; Abdullah; Abe; Abel; Abelardo; Abner; Abraham; Adah; Adalberto; Adam; Adan; Addison; Adelbert; Adell; Adolf; Adolfo; Adolph; Adolphus; Adonis; Adrain; Adrian; Adriel; Adrien; Afton; Aglae; Agustin; Ahmad; Ahmed; Aidan; Aiden; Akeem; Al; Alan; Alanis; Albert; Alberto; Albin; Alden; Alec; Aleen; Alejandrin; Alek; Alessandro; Alex; Alexander; Alexandre; Alexandro; Alexane; Alexzander; Alf; Alfonso; Alfonzo; Alford; Alfred; Alfredo; Ali; Allan; Allen; Alphonso; Alvah; Alvis; Amani; Amari;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstMale {
            get {
                return ResourceManager.GetString("FirstMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbott; Abernathy; Abshire; Adams; Altenwerth; Anderson; Ankunding; Armstrong; Auer; Aufderhar; Bahringer; Bailey; Balistreri; Barrows; Bartell; Bartoletti; Barton; Bashirian; Batz; Bauch; Baumbach; Bayer; Beahan; Beatty; Bechtelar; Becker; Bednar; Beer; Beier; Berge; Bergnaum; Bergstrom; Bernhard; Bernier; Bins; Blanda; Blick; Block; Bode; Boehm; Bogan; Bogisich; Borer; Bosco; Botsford; Boyer; Boyle; Bradtke; Brakus; Braun; Breitenberg; Brekke; Brown; Bruen; Buckridge; Carroll; Carter; Cartwright; Casper;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.;Mrs.;Ms.;Miss;Dr.;Prof..
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs.;Ms.;Miss;Dr.;Prof..
        /// </summary>
        internal static string PrefixFemale {
            get {
                return ResourceManager.GetString("PrefixFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.;Dr.;Prof..
        /// </summary>
        internal static string PrefixMale {
            get {
                return ResourceManager.GetString("PrefixMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jr.;Sr.;I;II;III;IV;V;MD;DDS;PhD;DVM.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
    }
}
